services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
    public: false

  WechatMiniProgramStatsBundle\Command\:
    resource: '../../Command/'
  WechatMiniProgramStatsBundle\Controller\:
    resource: '../../Controller/'
  WechatMiniProgramStatsBundle\EventSubscriber\:
    resource: '../../EventSubscriber/'
  WechatMiniProgramStatsBundle\MessageHandler\:
    resource: '../../MessageHandler/'
  WechatMiniProgramStatsBundle\Procedure\:
    resource: '../../Procedure/'
  WechatMiniProgramStatsBundle\Repository\:
    resource: '../../Repository/'
  WechatMiniProgramStatsBundle\Service\:
    resource: '../../Service/'

